import Head from 'next/head'
import Nav from '@/components/Nav'
import Hero from '@/components/Hero'
import Featured from '@/components/Featured'
import Works from '@/components/Works'
import client from "@/sanityClient"

// import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home({ gallery }) {
  return (
    <>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main >
        <Nav></Nav>
        <Hero></Hero>
        <Featured></Featured>
        <Works gallery={gallery}></Works>
        <div className="h-screen"></div>
      </main>
    </>
  )
}

export async function getStaticProps() {

  const heroSection = await client.fetch(`*[_type=="heroSection"][0]{heroHeading,heroParagraph,heroCTA}`);
  const gallery = await client.fetch(`*[_type=="gallery"]`);
  const pricing = await client.fetch(`*[_type=="pricing"]`);

  return {
    props: {
      heroSection,
      gallery,
      pricing
    }
  };
}
